# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cpark <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/03/21 16:43:59 by cpark             #+#    #+#              #
#    Updated: 2017/03/22 13:30:37 by cpark            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_advanced_do-op

SRC = ft_put.c ft_atoi.c ft_cala.c ft_calb.c ft_doop.c

all : $(NAME)

$(NAME) :
	gcc -Wextra -Wall -Werror -o $(NAME) $(SRC)

clean :
	/bin/rm -f $(NAME)

re : clean all
