# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: cpark <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/03/21 13:44:22 by cpark             #+#    #+#              #
#    Updated: 2017/03/22 13:29:24 by cpark            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = ft_put.c ft_atoi.c ft_doop.c

all : $(NAME)

$(NAME) :
	gcc -Wextra -Wall -Werror -o $(NAME) $(SRC)

clean :
	/bin/rm -f $(NAME)

re : clean all
